### Disable / hide the hud by default
no_display

### Limit the application FPS. Comma-separated list of one or more FPS values (e.g. 0,30,60). 0 means unlimited (unless VSynced)
fps_limit=165,30,60

### VSync [0-3] 0 = adaptive; 1 = off; 2 = mailbox; 3 = on
vsync=3

### Time config
time
time_no_label
time_format=%F %T

### Other parameters
gpu_name
gpu_stats
gpu_temp
cpu_stats
cpu_temp
fps

### Font
font_size=16
text_outline
width=0
background_alpha=0.4

### Hotkeys
toggle_hud=Shift_R+F12
toggle_fps_limit=
toggle_hud_position=
toggle_preset=
toggle_logging=
reload_cfg=
upload_log=
reset_fps_metrics=
